version: '3.9'

services:
  java_app:
    container_name: java_app
    image: gym-java-app:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL:-jdbc:postgresql://java_db:5432/gymappdb}
      - SPRING_DATASOURCE_URL=${DATABASE_URL:-jdbc:postgresql://java_db:5432/gymappdb}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME:-root}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD:-61945}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-root}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-61945}
    depends_on:
      - java_db
    restart: on-failure

  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-root}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-61945}
      POSTGRES_DB: ${POSTGRES_DB:-gymappdb}
    volumes:
      - ./data/db:/var/lib/postgresql/data
